openapi: 3.0.0
info:
  title: Rails REST-API
  version: 1.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
  - name: JWT API
  - name: User API
paths:
  /jwt/:
    post:
      tags:
        - JWT API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  required: true
                  example: taro@email.com
                password:
                  type: string
                  required: true
                  example: Taro1234
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: Json.Web.Token
  /user/:
    get:
      tags:
        - User API
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    example: taro@email.com
                  name:
                    type: string
                    example: Taro
    post:
      tags:
        - User API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  required: true
                  example: taro@email.com
                password:
                  type: string
                  required: true
                  example: Taro1234
                name:
                  type: string
                  required: true
                  example: Taro
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: Success
    patch:
      tags:
        - User API
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                param:
                  type: string
                  required: true
                  example: name
                current_val:
                  type: string
                  required: true
                  example: Taro
                new_val:
                  type: string
                  required: true
                  example: Jiro
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: Success
    delete:
      tags:
        - User API
      security:
        - bearerAuth: []
      responses:
        '204':
          description: No Content
